### ISSUE TITLE
vue-plugin causes error

### ISSUE THREAD

**Issue by ddweber** [stalniy/casl-vue-example#1]
Hello, first of all thank you for sharing this project with us :)

I have a problem when i´m trying to use the vue-plugin in my application.

I have build my abilities like in this example, but i´m getting the following error, when i´m trying to run the application.

_ability.on is not a function_

**Comment by stalniy** [comment]
Hello,

This is probably because you use old version of casl. 
Ability.on was added in 1.1.0, so you either need to update package.json or package-lock.json

**Comment by stalniy** [comment]
I plan to publish a separate package for Vue soon. Hopefully it will solve your issue

**Comment by ddweber** [comment]
Hello, thanks for your reply.
My version of casl is and was up to date.

That are some good news! Thanks a lot for all your work.

**Comment by stalniy** [comment]
@ddweber `@casl/Vue` is available on npm you can test it in your example and let me know whether the issue exists
